### ISSUE TITLE
Integration with any mapping library like Automapper

### ISSUE THREAD

**Issue by harshitgindra** [csharpfritz/InstantAPIs#56] opened 2022-03-11 07:56 UTC
It'd be a good enhancement to configure it with a mapper to map database model to view model and vice versa. 
Mappers like Automapper

**Comment by ScottKane** [comment] 2022-03-24 00:49
same as #53. I would say Automapper is a good choice though

**Comment by csharpfritz** [comment] 2022-04-04 18:11
Duplicate of #53

**Closed by csharpfritz** 2022-04-04 18:11 UTC
